export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';
export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE';
export const SET_SEARCH_TRIGGER = 'SET_SEARCH_TRIGGER';
export const SET_SEARCH_PEOPLE = 'SET_SEARCH_PEOPLE'
export const SET_SEARCH_START = 'SET_SEARCH_START'
export const SET_SEARCH_END = 'SET_SEARCH_END'
export const SET_SEARCH_LOCATION = 'SET_SEARCH_LOCATION'
export const SET_SEARCH_PAGE = 'SET_SEARCH_PAGE'

